# Generated by Django 4.1.5 on 2023-07-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.TextField(),
        ),
    ]
