# Generated by Django 4.1.5 on 2023-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apii', '0002_alter_employee_password_alter_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('Product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Groceries', 'Groceries')], max_length=50)),
                ('size_or_weight', models.CharField(blank=True, choices=[], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
