# Generated by Django 4.1.5 on 2023-10-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apii', '0003_cart_product_alter_employee_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
