# Generated by Django 4.1.5 on 2023-10-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apii', '0005_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
