# Generated by Django 4.1.5 on 2023-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apii', '0006_delete_employee_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
