# Generated by Django 4.1.5 on 2023-10-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apii', '0007_alter_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
